server:
  port: 8083

#JDBC Properties for MySQL
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3308/bill
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Eureka Discovery Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka
  instance:
    hostname: localhost