#Service Port
server:
  port: 8888

#Application name
spring:
  application:
    name: admin-config

#local config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: /app/data.server.config

          ##file:/C:/Users/AHINCAPIE/Desktop/MS-SuperMarket/data.server.config


