services:
  BillManagementMySQL:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: bill
    volumes:
      - data-mysqlBill:/var/lyb/mysql
    restart: always

  ProductManagementMySQL:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: product
    volumes:
      - data-mysqlProduct:/var/lyb/mysql
    restart: always

  CustomerManagementMySQL:
    image: mysql:latest
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: customer
    volumes:
      - data-mysqlCustomer:/var/lyb/mysql
    restart: always

  admin.config:
    image: admin-config:v1
    ports:
      - "8888:8888"
    restart: always

  management.customer:
    image: management-customer:v1
    ports:
      - "8082:8082"
    depends_on:
      - CustomerManagementMySQL
      - admin.config
      - registry.server
    restart: always

  registry.server:
    image: registry-server:v1
    ports:
      - "8889:8889"
    depends_on:
      - admin.config
    restart: always

volumes:
  data-mysqlBill:
  data-mysqlProduct:
  data-mysqlCustomer:

