services:
  BillManagementMySQL:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: bill
    volumes:
      - data-mysqlBill:/var/lyb/mysql
    restart: always

  ProductManagementMySQL:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: product
    volumes:
      - data-mysqlProduct:/var/lyb/mysql
    restart: always

  CustomerManagementMySQL:
    image: mysql:latest
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: customer
    volumes:
      - data-mysqlCustomer:/var/lyb/mysql
    restart: always

  admin.config:
    image: admin-config:v1
    ports:
      - "8888:8888"
    restart: always

  registry.server:
    image: registry-server:v1
    ports:
      - "8889:8889"
    depends_on:
      - admin.config
    restart: always

  administration.api.gateway:
    image: administration-api-gateway:v1
    ports:
      - "8887:8887"
    depends_on:
      - admin.config
    restart: always

  administration.server:
    image: administration-server:v1
    ports:
      - "8890:8890"
    depends_on:
      - admin.config
    restart: always


  management.customer:
    image: management-customer:v1
    ports:
      - "8082:8082"
    depends_on:
      - CustomerManagementMySQL
      - admin.config
      - registry.server
    restart: always

  management.product:
    image: management-product:v1
    ports:
      - "8081:8081"
    depends_on:
      - ProductManagementMySQL
      - admin.config
      - registry.server
    restart: always

  management.bill:
    image: management-bill:v1
    ports:
      - "8083:8083"
    depends_on:
      - BillManagementMySQL
      - admin.config
      - registry.server
    restart: always



volumes:
  data-mysqlBill:
  data-mysqlProduct:
  data-mysqlCustomer:

