server:
  port: 8887

# Eureka Discovery Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8889/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:

      enabled: true
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true