#Server Port config
server:
  port: 8081

#JDBC Properties for MySQL
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://host.docker.internal:3307/product
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Eureka Discovery Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8889/eureka

  # Admin Client
  boot:
    admin:
      client:
        url: http://host.docker.internal:8890
        instance:
          management-base-url: http://host.docker.internal:8081

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:

      enabled: true
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true