server:
  port: 8083

#JDBC Properties for MySQL
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://host.docker.internal:3308/bill
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Eureka Discovery Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8889/eureka


#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:

      enabled: true
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true